//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Catalog.Models
{
    using System.ComponentModel.DataAnnotations;

    
    public partial class STUDENT
    {
        public int SID { get; set; }

        [Required(ErrorMessage = "This field is required."), MaxLength(15)]
        public string SFIRSTNAME { get; set; }

        [Required(ErrorMessage = "This field is required."), MaxLength(15)]
        public string SLASTNAME { get; set; }

        public string GENDER { get; set; }

        [MaxLength(35)]
        public string ADDRESS { get; set; }

        [MaxLength(25)]
        public string CITY { get; set; }

        public string DEPARTMENT { get; set; }

        [MaxLength(35)]
        public string SCHOOL { get; set; }

        [MaxLength(15)]
        public string PFIRSTNAME { get; set; }

        [MaxLength(15)]
        public string PLASTNAME { get; set; }

        [MaxLength(14)]
        public string PHONE_NUMBER { get; set; }

        [Required(ErrorMessage = "This field is required."), MaxLength(15)]
        public string DATE_ENROLLED { get; set; }

        public string ATTENDANCE { get; set; }
    }
}
