//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus_Catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_DELETED
    {
        public int SID { get; set; }
        public string SFIRSTNAME { get; set; }
        public string SLASTNAME { get; set; }
        public string GENDER { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string DEPARTMENT { get; set; }
        public string SCHOOL { get; set; }
        public string PFIRSTNAME { get; set; }
        public string PLASTNAME { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string DATE_ENROLLED { get; set; }
        public string ATTENDANCE { get; set; }
    }
}
